// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: service.proto

package twooterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTwootRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Twoot to create.
	Twoot         *Twoot `protobuf:"bytes,1,opt,name=twoot,proto3" json:"twoot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTwootRequest) Reset() {
	*x = CreateTwootRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTwootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTwootRequest) ProtoMessage() {}

func (x *CreateTwootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTwootRequest.ProtoReflect.Descriptor instead.
func (*CreateTwootRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTwootRequest) GetTwoot() *Twoot {
	if x != nil {
		return x.Twoot
	}
	return nil
}

type ListTwootsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTwootsRequest) Reset() {
	*x = ListTwootsRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTwootsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTwootsRequest) ProtoMessage() {}

func (x *ListTwootsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTwootsRequest.ProtoReflect.Descriptor instead.
func (*ListTwootsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

type ListTwootsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Twoots.
	Twoots        []*Twoot `protobuf:"bytes,1,rep,name=twoots,proto3" json:"twoots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTwootsResponse) Reset() {
	*x = ListTwootsResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTwootsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTwootsResponse) ProtoMessage() {}

func (x *ListTwootsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTwootsResponse.ProtoReflect.Descriptor instead.
func (*ListTwootsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListTwootsResponse) GetTwoots() []*Twoot {
	if x != nil {
		return x.Twoots
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\atwooter\x1a\x0eresource.proto\":\n" +
	"\x12CreateTwootRequest\x12$\n" +
	"\x05twoot\x18\x01 \x01(\v2\x0e.twooter.TwootR\x05twoot\"\x13\n" +
	"\x11ListTwootsRequest\"<\n" +
	"\x12ListTwootsResponse\x12&\n" +
	"\x06twoots\x18\x01 \x03(\v2\x0e.twooter.TwootR\x06twoots2\x90\x01\n" +
	"\aTwooter\x12<\n" +
	"\vCreateTwoot\x12\x1b.twooter.CreateTwootRequest\x1a\x0e.twooter.Twoot\"\x00\x12G\n" +
	"\n" +
	"ListTwoots\x12\x1a.twooter.ListTwootsRequest\x1a\x1b.twooter.ListTwootsResponse\"\x00B,Z*github.com/tedsilb/twooter/proto/twooterpbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(*CreateTwootRequest)(nil), // 0: twooter.CreateTwootRequest
	(*ListTwootsRequest)(nil),  // 1: twooter.ListTwootsRequest
	(*ListTwootsResponse)(nil), // 2: twooter.ListTwootsResponse
	(*Twoot)(nil),              // 3: twooter.Twoot
}
var file_service_proto_depIdxs = []int32{
	3, // 0: twooter.CreateTwootRequest.twoot:type_name -> twooter.Twoot
	3, // 1: twooter.ListTwootsResponse.twoots:type_name -> twooter.Twoot
	0, // 2: twooter.Twooter.CreateTwoot:input_type -> twooter.CreateTwootRequest
	1, // 3: twooter.Twooter.ListTwoots:input_type -> twooter.ListTwootsRequest
	3, // 4: twooter.Twooter.CreateTwoot:output_type -> twooter.Twoot
	2, // 5: twooter.Twooter.ListTwoots:output_type -> twooter.ListTwootsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_resource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
