# This workflow will do a clean install of node dependencies, run a prod build, and run all tests
# For more info: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# See supported Node.js release schedule at https://nodejs.org/en/about/releases/

name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v5.0.0

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json

      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build:prod
      - run: pnpm run test:ci
